// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005203306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleGroup = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            MuscleGroup = "Legs",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 3,
                            MuscleGroup = "Back",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 4,
                            MuscleGroup = "Shoulders",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 5,
                            MuscleGroup = "Back",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 6,
                            MuscleGroup = "Back",
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = 7,
                            MuscleGroup = "Biceps",
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = 8,
                            MuscleGroup = "Triceps",
                            Name = "Tricep Extension"
                        },
                        new
                        {
                            Id = 9,
                            MuscleGroup = "Shoulders",
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            Id = 10,
                            MuscleGroup = "Legs",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 11,
                            MuscleGroup = "Legs",
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = 12,
                            MuscleGroup = "Legs",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 13,
                            MuscleGroup = "Calves",
                            Name = "Calf Raise"
                        });
                });

            modelBuilder.Entity("api.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("api.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("api.Models.WorkoutSet", b =>
                {
                    b.HasOne("api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });
#pragma warning restore 612, 618
        }
    }
}
